# Generated by Django 2.2.1 on 2019-05-11 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact', models.BooleanField(default=False, help_text='가맹점일 경우 체크하시오.')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice', models.TextField(blank=True)),
                ('spec', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True)),
                ('seatImage', models.ImageField(blank=True, upload_to='seat_images/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.Room')),
            ],
        ),
    ]
